### ISSUE TITLE
Update README with new logo banner

### ISSUE THREAD

**Issue by mcturco** [asyncapi/template-for-generator-templates#172]
#### Reason/Context
This is to replace the old AsyncAPI logo in this repo's README with the banner attached below that represents the new branding.

**Here are a few guidelines for this change as well:**
1. Make sure you are using [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) only
2. Be sure to remove the old logo as well as the old title of the repo as this image will replace both elements
3. Make sure you link this image to the website: `https://www.asyncapi.com`
4. If there is any description text below the repo title, let's make it left-aligned if it isn't already, so as to match the left-alignment of the content in the new banner image

**Download the image file:**
[github-repobanner-generic.png.zip](https://github.com/asyncapi/template-for-generator-templates/files/8233269/github-repobanner-generic.png.zip)

------

#### Banner preview
_Please note that this is only a preview of the image, the contributor should download and use the above zip file_ 

<img width="830" alt="github-repobanner-generic" src="https://user-images.githubusercontent.com/60163079/157898691-73dc7c1a-bf82-4c91-a89b-67e88bba7293.png">

**Comment by derberg** [comment]
@sancodes go ahead 🙏🏼

**Comment by sancodes** [comment]
@derberg since  I will need to change the image, should I make a folder in this repo, that stores the new image? 

Before I was trying to store the image in the repo, `parser-js` , as thats what the image that we have now was stored in.

**Comment by derberg** [comment]
@sancodes go ahead, we call these repos `assets`

**Comment by sancodes** [comment]
@derberg Please help me review my PR. If anything is missing, I'm willing to fix it.
