### ISSUE TITLE
FetchError: request to https://raw.githubusercontent.com/asyncapi/generator/v1.0.1/test/docs/dummy.yml

### ISSUE THREAD

**Issue by emeraldhieu** [asyncapi/template-for-generator-templates#347]
### Describe the bug.

```
[~]$ ag https://raw.githubusercontent.com/asyncapi/generator/v1.0.1/test/docs/dummy.yml https://github.com/asyncapi/template-for-generator-templates -o output
(node:4244) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Something went wrong:
FetchError: request to https://raw.githubusercontent.com/asyncapi/generator/v1.0.1/test/docs/dummy.yml failed, reason: 
    at ClientRequest.<anonymous> (/Users/nguyenduchieu/.nvm/versions/node/v22.7.0/lib/node_modules/@asyncapi/generator/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:520:28)
    at emitErrorEvent (node:_http_client:103:11)
    at TLSSocket.socketErrorListener (node:_http_client:506:5)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
```

### Expected behavior

Succeed with no error

### Screenshots

<img width="1002" alt="Screenshot 2024-09-04 at 11 15 23" src="https://github.com/user-attachments/assets/202ea27c-99cd-4e0b-b151-5dff6f913dac">

### How to Reproduce

Run
```
ag https://raw.githubusercontent.com/asyncapi/generator/v1.0.1/test/docs/dummy.yml https://github.com/asyncapi/template-for-generator-templates -o output
```

as described at https://github.com/asyncapi/template-for-generator-templates?tab=readme-ov-file#template-development-hints

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by emeraldhieu** [comment]
I tried again and got the incompatible version.

**Comment by derberg** [comment]
what `ag` version are you using. Also fetched resource is referenced correctly, are you sure you are not somewhere in internal company network behind some firewall that might block fetching?
